dataset:
    name: &dataset_name 'imagenet'
    root: &data_dir './resource/data/ILSVRC2012/'
    data:
        train: !join [*data_dir, 'train.txt']
        valid: !join [*data_dir, 'valid.txt']
        test: !join [*data_dir, 'valid.txt']
    num_workers: 16
    normalizer:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

input_shape: [3, 299, 299]

org_model:
    type: &org_type 'inception_v3'
    config: !join ['./config_imagenet/', *org_type, '.yaml']
    partition_idx: 17

autoencoder:
    type: &ae_type 'middle_ae'
    params:
        input_channel: 192
        bottleneck_channel: &bottleneck_channel 12
    experiment: &ae_experiment !join [*dataset_name, '-', *ae_type, '-b', *bottleneck_channel, 'ch-', *org_type]
    ckpt: !join ['resource/ckpt/ae/', *ae_experiment, '.pt']

train:
    epoch: 20
    batch_size: 32
    rough_size: 327
    interval: -1
    optimizer:
        type: 'Adam'
        params:
            lr: 0.001
    scheduler:
        type: 'MultiStepLR'
        params:
            milestones: [5, 10, 15]
            gamma: 0.1
    criterion:
        type: 'MSELoss'
        params:
            reduction: 'sum'

test:
    batch_size: 50
